<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup Label="Solver backends and integrations">
    <PackageVersion Include="Google.OrTools" Version="9.15.6755" />
    <PackageVersion Include="Gurobi.Optimizer" Version="13.0.3" />
    <PackageVersion Include="Highs.Native" Version="1.15.1" />
    <PackageVersion Include="Microsoft.Z3" Version="4.12.2" />
    <PackageVersion Include="NodaTime" Version="3.3.4" />
  </ItemGroup>

  <ItemGroup Label="Testing">
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>

</Project>
